### ISSUE TITLE
Face discoloration when equip npc item

### ISSUE THREAD

**Issue by lolbleach001** [Synthesis-Collective/SynthEBD#116] opened 2023-04-02 08:07 UTC
Discoloration face when equip item in npc. enabled ebd scripts and blocked mods head parts and didn't fix it

**Comment by Piranha91** [comment] 2023-04-02 13:29
How are you equipping items to NPCs? Is it all items, or a specific item or type?

**Comment by lolbleach001** [comment] 2023-04-02 20:51
Outfit NPCs (Inventory-Equipment) SE. There are also moments where the game loads and the color of the face also changes

**Comment by lolbleach001** [comment] 2023-04-06 04:39
any solution?

**Comment by lolbleach001** [comment] 2023-04-06 04:39
> Outfit NPCs (Inventory-Equipment) SE. There are also moments where the game loads and the color of the face also changes

**Comment by Piranha91** [comment] 2023-04-07 16:05
If you update to 1.0.0.2 using a clean save, does the issue still occur?

**Comment by Piranha91** [comment] 2023-04-09 01:45
This issue should be resolved in version 1.0.0.3 (requires a clean save, or new game). Thanks for providing the mod to reproduce it.

**Comment by Piranha91** [comment] 2023-04-23 17:52
Closed due to inactivity.

**Closed by Piranha91** 2023-04-23 17:52 UTC
