### ISSUE TITLE
SynthEBD not correctly changing custom NPC's body/hand/feet .nif paths?

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#65] opened 2022-12-03 04:19 UTC
Hi again,

This time I'm trying to use SynthEBD to patch Custom NPCs in order to force them all to use vanilla body meshes and my own list of BodySlides/Textures through Body Descriptor and Textures rules.

However, I noticed that in-game some of these NPCs aren't getting the right bodies, sometimes a very weird one. Forcing a Bodyslide using AutoBody's hotkey sometimes work, but when it does, they quickly revert to old body after some event refresh.

Checking with SSEEdit, I've noticed that SynthEBD is correctly overwriting the NPC's Mod .esp "torso" entries of the "Armor Addon" section (shouldn't  it overwrite hands and feet also?) with the vanilla torso .nif path. However, that looks like it is being ignored, since I've also noticed that  SynthEBD overwrites the NPC's WNAM/Worn Armor record with its own NPC_Patched0001 ARMO record. This record then points me to another Body_Patched0001 record that has, among other entries, three ARMA records (torso,feet,hands) where each has Model Filename entries pointing to the custom NPCs torso/hands/feet .nif path, and not the vanilla paths... shoudln't all of these paths point to the vanilla one, since I chose the "force" option on SynthEBD to use vanilla meshes?

These were all vanilla Races NPCs. On a side note, I did test on one custom race NPC, and its "Armor Addon" entry wasn't even overwritten by SynthEBD like the other vanilla races NPCs. I also made sure to include its custom race to the patchable races list...

I'm sorry if the explanation got a bit convoluted, I don't have a good understanding of Skyrim's inner working :)

I ran the patcher with these options turned on:
![image](https://user-images.githubusercontent.com/13605450/205422100-0eeb3742-07d4-4170-9551-dc79a52000af.png)

Thanks!

**Comment by Piranha91** [comment] 2022-12-03 07:32
That does sound like incorrect behavior - can I ask 2 favors to help with debugging? 1) can you upload screenshots of what you are describing in SSEedit? 2) can you tell me which follower it is so I can download and test?

regarding the follower though, keep in mind that config files are race restricted as well. Usually the head normal maps are specific to races (eg breton normals only go to Breton NPCs). That means that if there are no head normals whose allowed races include the custom race NPC, the whole config file will be deemed incompatible). The easiest way around this is to use the race aliasing feature in the general settings menu - if you want that follower to get Nord textures, for example, you would alias the custom follower race as NordRace. My hunch is this should resolve your issue.

**Comment by leonardovcr** [comment] 2022-12-03 21:44
Sure, I'm using Somollig's NPCs converted to SSE and I've merged them into one .esp via zEdit's merge.

Somollig's original NPC's: https://www.nexusmods.com/skyrim/users/57455561?tab=user+files

Some SSE's conversions:
https://www.nexusmods.com/skyrimspecialedition/mods/46789?tab=description
https://www.nexusmods.com/skyrimspecialedition/mods/35077?tab=description
https://www.nexusmods.com/skyrimspecialedition/mods/48822?tab=description

These are the entries for "Charlotte" for example:

![image](https://user-images.githubusercontent.com/13605450/205462641-f3e0206e-e549-4587-9000-4ed12e61445e.png)
![image](https://user-images.githubusercontent.com/13605450/205462709-b7efccd9-b506-4ff9-8836-76f52f16be7b.png)
![image](https://user-images.githubusercontent.com/13605450/205462745-1f35021c-60f0-49fe-8836-f92193c33a0e.png)
![image](https://user-images.githubusercontent.com/13605450/205462777-aace5c49-e7e5-4e5f-8436-283303da8eb8.png)
![image](https://user-images.githubusercontent.com/13605450/205462795-b79ad54c-b4bd-4fa5-8eec-e615d4e7830e.png)

About the custom race NPC, it was as you said, my conf was lacking the race alias... Now it looks like it is patching correctly. I didn't have time to do some thorough testing, but from what I could see, there was some weird body stretching and some mismatch between hands and body. I'sm still trying to debug it properly though...

**Comment by Gawdzila** [comment] 2022-12-05 23:03
I can confirm that I am experiencing the same sort of issue with EasyNPC, with actors inheriting the old body meshes. The body textures do appear to work correctly, but the face textures are still being inherited from EasyNPC.  I am using the EasyNPC Compatibility Mode.

Interestingly, I took a peek in SSEEdit and it looks as if there is a copy of the EasyNPC torso armor record, with the same name as the one in the EasyNPC, being created with vanilla paths that has the same name as the one in the EasyNPC record, but that one is not being used.  Instead, another version with "_Patched0001" appended to the name is being used, and that one contains the old path for the custom body that is packed into the EasyNPC .bsa file.  I was doing some testing with the BijinNPCs mod and, weirdly, if I load the mod but disable the .esp from it, SynthEBD then replaces the body properly. I have never been able to get it to stop using the Bijin face textures, however, even when I was not using EasyNPC at all.

**Comment by Gawdzila** [comment] 2022-12-06 05:28
Yes, exactly.  EasyNPC first, which I use as the input to SynthEBD, and then placing the generated SynthEBD plugin after the EasyNPC plugin so that it wins conflicts when running the game.

**Comment by Piranha91** [comment] 2022-12-06 06:39
That’s really weird - the body nif path issue I’ve reproduced and am in process of fixing, but I’ve never seen it fail to assign a face texture. Does the consistency entry for that NPC say it should have a modded face tex?

**Comment by Piranha91** [comment] 2022-12-06 08:50
The nif paths should now be working in 0.8.4.2. That said, I tested with Charlotte and I'm seeing a neck seam. Don't have a lot of time to dig into it - will try to look tomorrow to determine if it's just a bad texture combination in my testing or if there's some reason the script isn't applying to her. If it's an issue with the code I'll work on a fix asap. She's the only one in my testing who didn't get the script applied to her; not sure from a quick glance what's going on.

I still can't reproduce the issue of SynthEBD not applying a modded face texture. I'll need some screenshots to try to reproduce.

**Comment by Gawdzila** [comment] 2022-12-06 08:56
It certainly seems to -- it would be weird if it didn't, since I did a specific NPC assignment to some of them :)  I've been trying to diagnose it and see if some other mod is messing things up, but I've tried to avoid that by loading both EasyNPC and SynthEBD at the very bottom of both my load orders and all other NPC mods are deactivated.  I'll get you some screen shots when I get a chance.

**Comment by Gawdzila** [comment] 2022-12-06 23:00
Okeedokee, here's some screenies showing the face texture issue.  Figures the weird unheard-of problem would happen to me 😋 I've provided screenshots of Gerdur but most NPCs don't appear to be getting new face textures, not just the ones from Bijin mods; there are a lot of very prominent neck seams around.

Here's Gerdur, clearly with the original Bijin skin texture that contrasts with the texture assigned to her torso:
![20221206_141238_MixedReality](https://user-images.githubusercontent.com/119834693/206039715-b10db7e2-01ef-4a99-a836-caf92eafee5a.jpg)

Here's the bottom of my load order, showing that BijinNPCs is not loaded and that the EasyNPC merge and SynthEBD are at the bottom:
![LoadOrder](https://user-images.githubusercontent.com/119834693/206039885-a62065fc-7806-49df-9988-d603c3984b28.JPG)

Here are my SynthEBD settings showing the settings and consistency/assignments for Gerdur, who should be using the head diffuse from ALT2:
![Settings 1](https://user-images.githubusercontent.com/119834693/206040043-804a59a3-4d25-44c5-b0b2-1a04db9cf7d0.JPG)
![Settings 2](https://user-images.githubusercontent.com/119834693/206040081-6ee7138b-1fbb-4e61-951c-13b723bdf800.JPG)
![Settings 3](https://user-images.githubusercontent.com/119834693/206040127-458888b5-972f-4c31-88ef-26885393f2b8.JPG)
![Settings 4](https://user-images.githubusercontent.com/119834693/206040163-587bc1ce-19c9-496c-8824-afdd80d21cc1.JPG)

Do let me know if there's anything else helpful that I can provide!

**Comment by Piranha91** [comment] 2022-12-07 00:02
I’m starting to wonder if I messed something up when I repackaged one of the EBD scripts to include Pragasette’s esl fix. I’ll try to look into it tonight.

**Comment by Piranha91** [comment] 2022-12-07 09:05
Did a little bit of testing on the Charlotte follower... I put a custom watermark on the Demoniac head and body skin textures that SynthEBD was assigning to her. They both showed up in-game, so the skins are being applied, but the neck seam persisted. I then deleted SynthEBD and just checked her default appearance, and I see a huge neck seam anyway. Is this not the case for you?

**Comment by leonardovcr** [comment] 2022-12-07 18:00
Yes the neck seam is there anyway. With or withour SynthEBD. I've switched to the "original" (https://www.nexusmods.com/skyrimspecialedition/mods/34938?tab=files&file_id=135097&nmm=1) and not the "v2" version. The neck seam is almost imperceptible on this version.

**Comment by leonardovcr** [comment] 2022-12-07 22:02
Piranha, I've noticed this custom body .nif reference still being used... is that ok?

![image](https://user-images.githubusercontent.com/13605450/206304032-2f4aea23-5628-4ff2-a46c-24f972730f12.png)
![image](https://user-images.githubusercontent.com/13605450/206304986-476fa4b4-2bd5-4044-a3f9-6fbecd591f1c.png)

It seems to happen with  [Pariahfolk13](https://www.nexusmods.com/skyrimspecialedition/users/66346026)'s NPCs, like Vorgha for example (https://www.nexusmods.com/skyrimspecialedition/mods/77812?tab=description).

**Comment by Piranha91** [comment] 2022-12-07 22:28
Is that model actually being used, or is there a torso Armature that’s superseding it in game?

**Comment by leonardovcr** [comment] 2022-12-07 23:00
Stupid me sent screens of different NPCs... -_-

These are Vorgha's entries:
![image](https://user-images.githubusercontent.com/13605450/206313607-ef21599f-a83f-4dd8-8727-f0e0bcfb918d.png)
![image](https://user-images.githubusercontent.com/13605450/206313666-7acf6cf9-7046-417f-abc6-d95eda892b84.png)
![image](https://user-images.githubusercontent.com/13605450/206313792-d87b2942-5265-43bf-84ef-525f33ac4a77.png)

Vorgha is fine. I even removed the body/hands/head .nif/.dds files from the mod, and the body and armor meshes still loads ok, with the custom SynthEBD's patched textures.

However, Pariahfolk13's **Inga** NPC is being patched differently:

![image](https://user-images.githubusercontent.com/13605450/206314643-11e138e4-51bc-4034-bfe8-b54432d9cc98.png)
![image](https://user-images.githubusercontent.com/13605450/206314718-0fb8bb6a-2212-4806-a057-7eddd8169393.png)
![image](https://user-images.githubusercontent.com/13605450/206314827-1b4a7396-282d-4c4b-96a0-fcfd3de7e1e3.png)

In this case, the default NPC appearance with armor loads the mod's textures. Without armor, it gets SynthEBD's textures and body meshes. Removing the mod's body/hand/head .nif and .dds gives me a blue body with armor on, and SynthEBD's body/texture without armor.

**Comment by Piranha91** [comment] 2022-12-07 23:14
Link me to the mod so I can take a look on my end?

**Comment by leonardovcr** [comment] 2022-12-07 23:16
Sure

https://www.nexusmods.com/skyrimspecialedition/mods/76332?tab=description Morgan
https://www.nexusmods.com/skyrimspecialedition/mods/78364?tab=description Inga

**Comment by Gawdzila** [comment] 2022-12-08 06:07
I just tested by disabling SynthEBD and, while there is still a subtle seam, it seems consistent with the ones in the Bijin mod screenshots and it is much less pronounced than when I enable the SynthEBD plugin.  To be sure it wasn't simply the ALT2 skin, I also changed her to Dibellan textures.

With SynthEBD:
![20221207_204940_MixedReality (2)](https://user-images.githubusercontent.com/119834693/206359792-ff60e54a-43b8-4948-a1e3-09a6013156e3.jpg)

Without SynthEBD:
![20221207_191832_MixedReality (2)](https://user-images.githubusercontent.com/119834693/206350651-25b33525-9a0d-44dd-8e56-8ccb91cb6c1a.jpg)


I took a look in SSEEdit to see if I could see what was going on and it does look like her head texture is being created and assigned properly, it just apparently isn't being applied in the game.
![Gerdur_SSEEdit 1](https://user-images.githubusercontent.com/119834693/206351380-431e7a05-2cfd-4c85-878f-095e6e7edb06.jpg)

![Gerdur_SSEEdit 2](https://user-images.githubusercontent.com/119834693/206351383-89f7fc29-e147-4b4e-8316-e5d047038b13.jpg)


Last two tests.  To force it to use Dibellan textures, I disabled both SynthEBD and EasyNPC, enabled the original Bijin mod, and swapped the textures manually to the Dibellan textures directly from the EBD folder, just to see what it should look like.  The seam is still surprisingly obvious and they're very similar, but you can see that the freckle texture is different -- check the 3 prominent freckles right between the eyebrows in Bijin which are missing here, and also along the hairline, plus the shading on the neck/clavicle seems to line up correctly unlike in the top image.

![20221207_211510_MixedReality (2)](https://user-images.githubusercontent.com/119834693/206365681-d7148fb4-43b8-41f7-9a6b-1d2d161d01fc.jpg)

Lastly, I did the "watermark" test and wrote in bright blue text on the forehead of the Dibellan head diffuse map located in the SynthEBD texture folder, then enabled EasyNPC and SynthEBD, and it looked exactly like the first picture. No watermark, so it looks like it isn't being used.

SynthEBD is at the very bottom of my load order and clearly it is overriding the body textures properly, so I'm at a loss as to why it wouldn't be doing the same for faces.  Any ideas?

**Comment by Piranha91** [comment] 2022-12-08 06:27
Two questions:

1) Do you have EBD installed, and do you see its scripts in your real or virtualized data folder?
2) If you disable your NPC merge and just use Bijin's Gerdur and run SynthEBD, does she get patched correctly?

**Comment by Piranha91** [comment] 2022-12-08 07:08
> Sure
> 
> https://www.nexusmods.com/skyrimspecialedition/mods/76332?tab=description Morgan https://www.nexusmods.com/skyrimspecialedition/mods/78364?tab=description Inga

I tested with Inga - I think this is something to do with her armor specifically. I tested by running SynthEBD on Aela, and painting a mark on the body textures assigned to her:

![image](https://user-images.githubusercontent.com/63175798/206381106-7562eebf-e0a7-43e4-aaf9-a697a6fade34.png)

![image](https://user-images.githubusercontent.com/63175798/206381154-d06201ec-f624-4af1-b5af-ff8c99eef5b0.png)

As you can see, that mark appears under her armor. When I did the same thing with Inga, this didn't happen. I put one mark on her default skin and another on her SynthEBD-assigned skin, and it's the default one that shows up while she's wearing armor. I don't have an understanding of where in the armor it points to the skin, but evidently that cuirass is pointing explicitly as her default skin, whereas Aela's uses whatever is underneath. I'm asking in the SkyrimMods discord server to see anyone can point me to what controls this, but I suspect it's on the side of the armor and therefore probably not within the scope of SynthEBD (although if it's controlled by the plugin and not by the .nif, I could potentially have SynthEBD detect the default outfit and auto-patch it). But I suspect it's controlled somewhere in the .nif.

**Comment by Gawdzila** [comment] 2022-12-08 07:22
1. Yes, I do have the original EBD installed and, if I look in the virtualized data folder tree in MO, I do see all 6 EBD scripts there.
2. I tried running SynthEBD with Bijin NPCs only -- no NPC merge and no other NPC mods -- and it did not patch her face texture.  One different thing it did do was to throw a couple of those errors on some random NPCs where it says they're gonna be re-randomized because of no compatible assets or somesuch, and then it spit out a new file into the overwrite called HeadPartDict3.json, but that all seems like expected behavior.

**Comment by Piranha91** [comment] 2022-12-08 07:28
> 1. Yes, I do have the original EBD installed and, if I look in the virtualized data folder tree in MO, I do see all 6 EBD scripts there.
> 
>     2. I tried running SynthEBD with Bijin NPCs only -- no NPC merge and no other NPC mods -- and it did not patch her face texture.  One different thing it did do was to throw a couple of those errors on some random NPCs where it says they're gonna be re-randomized because of no compatible assets or somesuch, and then it spit out a new file into the overwrite called HeadPartDict3.json, but that all seems like expected behavior.

I'm going to move this to a new issue to avoid cluttering, since it looks like it's a separate problem.

**Comment by leonardovcr** [comment] 2022-12-08 20:35
Humm.. I know nothing of how .nif files work, but by opening Inga's armor on NifSkope I could find the following texture references to Skyrim's default body textures (maybe it's set elsewehere in the .nif?):

![image](https://user-images.githubusercontent.com/13605450/206560167-93616ad6-49de-46e7-ac7f-202b5f81c0d1.png)
![image](https://user-images.githubusercontent.com/13605450/206560581-79619eb6-0162-477a-afb0-751b2e27eac4.png)

The only other place where I could find references to the mod's default skin is in the plugin itself, as shown on those last two screenshots of my last post ("Female World Model - Alternate Textures" references).

**Comment by Piranha91** [comment] 2022-12-09 08:57
I was able to get the correct skin to show up under the armor by changing the armor slots from 32 to 56. You'll need to do this in the armor record, the armature record, and the _0 and _1 .nif files. You can find instructions here: https://www.nexusmods.com/skyrimspecialedition/articles/2861 - note that inga's armor has a bunch of pieces in the .nif, and you have to do it for all of them. Also, I noticed her armor doesn't have .tri files for bodyslide, so I hope you weren't planning to use autobody or obody on her.

The simpler solution IMO is to just give her a different armor that doesn't have this issue.

**Comment by leonardovcr** [comment] 2022-12-09 14:18
Ah, nice catch... but oh well, that's too much hassle for one NPC lol

I'll go with your suggestion and just give her vanilla armor!

**Comment by Piranha91** [comment] 2022-12-19 09:25
I think the conversation in this thread has been resolved - remaining issues about neck seams are best discussed in the other open issue on this topic.

**Closed by Piranha91** 2022-12-19 09:25 UTC
