### ISSUE TITLE
Subgroup is deleting when I click on expand

### ISSUE THREAD

**Issue by HitBug83** [Synthesis-Collective/SynthEBD#26] opened 2022-07-11 23:04 UTC
And the last one : sometimes when I expand a subgroup on the tree, the whole subgroup is deleted. It happens _almost_ everytime when I expand a subgroup for the first time after launching SynthEBD. Then I discard change, and I can work on my config for some time, but it can happen again afterward. I have to save the config file every 2 minutes otherwise I'm almost sure to loose my work.

**Comment by Piranha91** [comment] 2022-07-12 00:31
I will examine this, but I've never had this happen before. What I have noticed is that because the + and - icons are so small, I occasionally hit one or the other on accident. Could this be what's happening? I can try moving the buttons a bit farther away from the subgroup name to help avoid mis-clicks.

**Comment by HitBug83** [comment] 2022-07-12 17:18
Here is a video of the issue, with the unmodified Mature Skin config you provide.

Doesn't seems to happen with Bijin or Mature Skin "light" subgroups like specular or subsurface. 

But it happens randomly after some time working on the config, and then my only solution is to discard all changes, including all the work I've done since the last manual save.

I guess fixing the memory issue would fix this as well ?

https://user-images.githubusercontent.com/109113269/178550670-1e277a9d-c736-40bf-8bf7-ebb3275a4127.mp4

**Comment by theemptycastle** [comment] 2022-07-24 03:05
+1 on this bug. I can't reliably reproduce it, but it seems to happen only once per session when it does happen. I have to replace the config files with backups/originals to get the config back to normal.

**Comment by Piranha91** [comment] 2022-07-24 04:03
Do you get it with the latest version? I could reproduce it occasionally before 0.7.7.2, but not since then. Will check again.

**Comment by Piranha91** [comment] 2022-07-24 06:51
Should be fixed in 0.7.8.

**Comment by HitBug83** [comment] 2022-07-24 10:28
I still have the issue with 0.7.8

I can confirm it is certainly a mouse input issue because the workaround I've found is to use the keyboard left/right arrows instead of the mouse. Another evidence against the mouse : I can sometimes see very briefly the cursor showing the same square it shows when I drag subgroups, right before the disappearance.

@theemptycastle you can discard changes at the bottom of the config

**Comment by Piranha91** [comment] 2022-07-24 17:58
Ok, 0.7.8.1 should prevent this. At least I sincerely hope so :D. After clicking around for about 10 minutes on the Mature Skins config with preview image size set to 4096 for maximum sluggishness, I was able to reproduce the issue. It's still technically a mis-click. Before, SynthEBD only allowed you to drag subgroups onto other subgroups. As I described above, when a parent was dragged onto a child it would disappear into a singularity. I plugged this - but then I added the ability to rearrange subgroups (something I've wanted to figure out how to do for ages!) - this then allowed the same bug, but where you'd click the expander arrow, move the mouse slightly down by a couple pixels, and unclick so the UI thought the parent was being dragged _before_ rather than _onto_ the child node, which I hadn't thought to prohibit. 0.7.8.1 should plug that hole. I really hope that was the only remaining potential cause, because I'd really have to rack my brains to figure out alternate hypotheses.

I really wonder why I have so much more trouble triggering this bug than you do. Maybe it's easier to do on a higher res screen where a slighter movement can change the target pixels. Anyway, hope this helps.

**Comment by theemptycastle** [comment] 2022-07-24 19:18
Awesome, thanks Piranha, great work. I was able to reprod the issue on 7.7.3 using the steps you described (clicking on a subgroup while moving the mouse slightly > subgroup disappears). In 7.8.1 I can't reprod with those steps, and drag & drop works as expected! Thanks again for all your hard work here, SynthEBD is a great tool.

**Comment by HitBug83** [comment] 2022-07-24 21:09
Another one bites the dust !

Thank you, it works fine now.

**Closed** 2022-07-25 02:44 UTC
