### ISSUE TITLE
(O)BodySlide distribution

### ISSUE THREAD

**Issue by Daikichi-Takahey** [Synthesis-Collective/SynthEBD#7] opened 2022-03-13 15:50 UTC
I want to distribute CBBE Strong preset to Aela, Njada, and Ria but it doesn't work. As usual, I can't explain it, so I hope you can watch the video.
https://www.youtube.com/watch?v=zj_K0hyZkrs
No matter how I compressed the video, I couldn't get it under 10MB, so please forgive the youtube link.
Skyrim SE 1.579 & Obody(Ostim version)

**Comment by Piranha91** [comment] 2022-03-14 06:45
Can confirm and reproduce. Looks like I did ForceIf filtering for Assets and BodyGen, but not for BodySlide. Should be a relatively quick fix; I'll try to do it early this week. In the meantime if you just have a small amount of NPCs you'd like to assign (Aela, Njada, Ria), you should be able to do it through the Specific NPC Assignments menu.

**Comment by Piranha91** [comment] 2022-03-20 21:50
Apologies for the delay; had an exceptionally busy week. Issue should now be fixed in 0.5.0.

**Closed by Piranha91** 2022-03-20 21:50 UTC
